### PR TITLE
Allow MenuItem url to be callable (rebased)

### PR DESCRIPTION
**Pull request by GabDug**
Hello,

I've taken the liberty to rebase what @timnyborg in #71 had done to make URLs callable, so that it can be merged for v2.X.

He is still the author of 2/3 commits, but has files moved not of the third.

Cheers!

### CODE REVIEW

**Comment by kytta** [comment]
Looks good to me. I'll merge it; the release should be out later today.

**Comment by GabDug** [comment]
Thanks for your reactivity @kytta !

I've noticed that neither 2.0.4 nor 2.1.0 are available on [pypi](https://pypi.org/project/django-simple-menu/#history). I don't know if something manual needs to be done on your side?

**Comment by kytta** [comment]
> I've noticed that neither 2.0.4 nor 2.1.0 are available on [pypi](https://pypi.org/project/django-simple-menu/#history). I don't know if something manual needs to be done on your side?

Yeah, I'm not the project lead, so I can submit releases for review but not publish them. For this, either @mbeijen or @borgstrom need to act on this.

**Comment by mbeijen** [comment]
Hi @kytta -- thanks for all your work on django-simple-menu
I've just uploaded the new releases on pypi.

BTW I would fully endorse you if you would like to become 'project manager' for the project, so you can release to pypi yourself!

**Pull request merged**
