### PR TITLE
chore: use pyproject.toml instead of setup.cfg

### PR DESCRIPTION
**Pull request by GabDug**
Small DX/packaging MR, following latest PEPs.

Using `pyproject.toml` and being PEP621-compliant will also make it easier to integrate with other dev-tools, like `PDM`.

### CODE REVIEW

**Comment by GabDug** [comment]
Unfortunately, it seems this approach does not work well for Python 3.6.

What are you thoughts on increasing the minimum Python version supported? Security support for 3.6 stopped on 23 Dec 2021, for 3.7 it was 2 months ago, lots of tools and libs now target 3.8-3.12.

**Comment by kytta** [comment]
> What are you thoughts on increasing the minimum Python version supported? Security support for 3.6 stopped on 23 Dec 2021, for 3.7 it was 2 months ago, lots of tools and libs now target 3.8-3.12.

Since Django 3.2 still supports Python 3.6, and we still support Django 3.2, we keep supporting Python 3.6 for the possible LTS users. So, we won't update the minimal version until 01 Apr 2024

**Comment by GabDug** [comment]
Understood.
Supporting 3.6 brings additional issues, as tox 4 only supports Python 3.7+ and latest setuptools only support 3.8+, while the CI only includes one Python version per job, so I'll close this PR.

**Comment by GabDug** [comment]
I agree that it should be doable, but I'm not sure it's worth it, it will probably add a lot of complexity for a Python version that's not gonna last a lot more!

I respect your commitment to support legacy Python versions, but to be honest, I don't share it: I believe that people that did not upgrade neither Python nor Django won't upgrade their dependencies.

Looking at how others projects handle this issue, I found the way django-taggit handles this, and it's [way simpler](https://github.com/jazzband/django-taggit/commit/1fd40e95ffc28057645d2d6c41aeac5cf358e868) 😂

Still I'll let you know if I find some time to look into the issue :)

**Comment by kytta** [comment]
> Looking at how others projects handle this issue, I found the way django-taggit handles this, and it's [way simpler](https://github.com/jazzband/django-taggit/commit/1fd40e95ffc28057645d2d6c41aeac5cf358e868) 😂

That is _genius_, how didn't I come up with this earlier?!

**Comment by GabDug** [comment]
Simpler than anticipated, also removed Django 4.0.

**Comment by GabDug** [comment]
Hey @kytta,

Small bump to the PR in case you have not seen the latest changes.
If you have, sorry for the notification! There's no rush here :) 

Have a nice day!

**Comment by kytta** [comment]
I hope I'll get to review this properly till the end of the week, otherwise you'll have to wait till October :D

**Review by kytta — APPROVED** [review]

**Pull request merged**
